### ISSUE TITLE
Resize Image for Mobile Responsive at Landing page

### ISSUE THREAD

**Issue by Tusharknwl** [Tusharknwl/Lumina_AI#2]
Currently, our landing page UI does not adapt well to different screen sizes, particularly on mobile devices. The banner image is not appropriately resized, leading to a suboptimal user experience.

![image](https://github.com/Tusharknwl/Lumina_AI/assets/72529636/7805851f-1b4f-40f0-bab5-497788829e66)

*Expected Result:*
- Image on the landing page should adapt to the screen size, providing a visually pleasing and user-friendly experience on mobile devices.

Additional Notes:
- It's important to maintain image quality while resizing.

**Comment by irfanfaraaz** [comment]
@Tusharknwl  Can I work on this?
